name = "SimplePackage"
uuid = "03240f09-871e-4687-9fc6-c70685b0bec9"
authors = ["Louis Reumaux"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
